version: "3.8"

services:

  jte-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jte-api
    restart: unless-stopped
    environment:
      DB_HOST: 172.17.0.1
      DB_PORT: 3306
      DB_USER: jte
      DB_PASS: Z@ry1548
      DB_NAME: jtemonitor
      JWT_SECRET: c3d042c47ea7252334c568a5f5d007b50a388f528825b85c40a116bcb63409a16c4577716e0b1a22bad55b208ee4e46bb908d89a4a53a91da33603b3b988881c
      JWT_ACCESS_EXPIRES: 15m
      JWT_REFRESH_DAYS: 7
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_SECURE: "false"
      SMTP_USER: ""
      SMTP_PASS: ""
      MAIL_FROM: "JTe Monitor <noreply@ativa.law>"
      PORT: 4000
      NODE_ENV: production
      FRONTEND_URL: https://ativa.law
      REDIS_HOST: 172.17.0.1
      REDIS_PORT: 6379
    ports:
      - "4000:4000"
    networks:
      - jte-network

  jte-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jte-frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: https://api.ativa.law
      PORT: 3085
      HOSTNAME: "0.0.0.0"
    ports:
      - "3085:3085"
    depends_on:
      - jte-api
    networks:
      - jte-network

networks:
  jte-network:
    driver: bridge